# Generated by Django 4.2.20 on 2025-05-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStat',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('last_requested', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
